analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 91149,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 77744,\\n  \\"status\\"\: \\"ACTIVE\\",\\n  \\"team\\"\: {\\n    \\"id\\"\: 77744,\\n    \\"name\\"\: \\"My Team\\",\\n    \\"organization\\"\: {\\n      \\"id\\"\: 82506,\\n      \\"name\\"\: \\"Ilham pandu putra\\",\\n      \\"samlSSO\\"\: false\\n    }\\n  },\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 77744,\\n  \\"name\\"\: \\"My Team\\",\\n  \\"organization\\"\: {\\n    \\"id\\"\: 82506,\\n    \\"name\\"\: \\"Ilham pandu putra\\",\\n    \\"samlSSO\\"\: false\\n  }\\n}"
analytics.testresult.autosubmit=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
